# Development Environment Configuration
# Overrides for development environment

app:
  environment: "development"
  debug: true
  maintenance_mode: false

# Development API Configuration
api:
  openai:
    model: "gpt-3.5-turbo"  # Use cheaper model for dev
    max_tokens: 2048
    timeout: 30
  
  anthropic:
    model: "claude-3-haiku-20240307"  # Faster model for dev
    max_tokens: 2048
    timeout: 30
  
  google:
    model: "gemini-1.5-flash"
    max_tokens: 2048
    timeout: 30

# Relaxed resource limits for development
resources:
  memory:
    max_memory_mb: 1024
    warning_threshold_mb: 768
    cleanup_threshold_mb: 896

  cpu:
    max_cpu_percent: 50
    max_concurrent_tasks: 2

  rate_limits:
    requests_per_minute: 30
    requests_per_hour: 500
    requests_per_day: 2000

  storage:
    max_disk_usage_gb: 5
    log_retention_days: 7

# Development-friendly retry policies
retry:
  global:
    max_attempts: 2
    base_delay: 0.5
    max_delay: 10.0

  services:
    llm_apis:
      max_attempts: 3
      base_delay: 1.0
      max_delay: 30.0

# Enhanced features for development
features:
  # Enable all validation for development
  validation:
    enabled: true
    syntax_validation: true
    logic_validation: true
    security_validation: true
    performance_validation: true

  # Disable external integrations by default
  integrations:
    notion_sync: false
    github_integration: false
    monitoring: false
    analytics: false

  # Enable experimental features
  experimental:
    advanced_reasoning: true
    multi_agent_collaboration: true
    predictive_caching: true
    auto_optimization: true

# Verbose logging for development
logging:
  level: "DEBUG"
  format: "detailed"
  
  outputs:
    console:
      enabled: true
      level: "DEBUG"
      format: "detailed"
      colorize: true
    
    file:
      enabled: true
      level: "DEBUG"
      format: "detailed"
      file_path: "logs/dev.log"
      max_size_mb: 50
      backup_count: 3

  components:
    orchestrator:
      level: "DEBUG"
      include_proposals: true
      include_voting: true
    
    agents:
      level: "DEBUG"
      include_prompts: true
      include_responses: true
    
    self_healing:
      level: "DEBUG"
      include_recovery_steps: true
      include_fixes: true
    
    validation:
      level: "DEBUG"
      include_test_results: true

# Relaxed security for development
security:
  authentication:
    required: false
  
  api_security:
    rate_limiting: false
    cors_enabled: true
    allowed_origins: ["*"]
  
  data_protection:
    encrypt_sensitive_data: false
    mask_api_keys_in_logs: false
  
  validation:
    validate_inputs: true
    sanitize_outputs: false
    check_malicious_patterns: false

# Performance settings optimized for development
performance:
  caching:
    enabled: true
    ttl_seconds: 1800  # 30 minutes
    max_cache_size_mb: 128

  concurrency:
    max_concurrent_requests: 5
    worker_threads: 2

  optimization:
    enable_profiling: true
    memory_profiling: true
    auto_gc: true

# Monitoring disabled for development
monitoring:
  metrics:
    enabled: false
  
  health_checks:
    enabled: true
    interval_seconds: 60
  
  alerting:
    enabled: false

# Development-specific settings
development:
  debug:
    verbose_logging: true
    include_stack_traces: true
    profile_execution: true
    save_intermediate_results: true

  testing:
    mock_external_apis: true
    use_test_data: true
    fast_mode: true
    skip_validations: false

  hot_reload:
    enabled: true
    watch_config: true
    watch_code: true
    reload_delay_ms: 500